// Game logic utilities for VVordigo
import { GeneratedPuzzle } from './puzzleGenerator';

export interface GameBlock {
  letter: string;
  id: string;
  row: number;
  col: number;
  isSelected: boolean;
  isHighlighted: boolean;
  wordId?: number;
}

export interface GameState {
  grid: GameBlock[][];
  selectedBlocks: GameBlock[];
  currentWord: string;
  score: number;
  timer: number;
  isGameComplete: boolean;
  gridSize: number;
  puzzleIndex: number;
  solution: string[];
  solutionPaths: number[][][];
  removedWords: string[];
  gameHistory: GameBlock[][][];
}

// Dictionary for word validation - in production, this would be a comprehensive dictionary
export const WORD_DICTIONARY = new Set([
  // 3-letter words
  'THE', 'AND', 'FOR', 'ARE', 'BUT', 'NOT', 'YOU', 'ALL', 'CAN', 'HER',
  'WAS', 'ONE', 'OUR', 'HAD', 'HAS', 'HIS', 'HOW', 'MAN', 'NEW', 'NOW',
  'OLD', 'SEE', 'TWO', 'WAY', 'WHO', 'BOY', 'DID', 'ITS', 'LET', 'PUT',
  'SAY', 'SHE', 'TOO', 'USE', 'DAD', 'MOM', 'BIG', 'END', 'WHY', 'LET',
  'OWN', 'SAW', 'MEN', 'DAY', 'GET', 'MAY', 'HIM', 'GOT', 'SUN', 'SET',
  'RUN', 'EAT', 'FAR', 'SEA', 'EYE', 'RED', 'TOP', 'ARM', 'OFF', 'BAD',
  'BAG', 'BED', 'BOX', 'CAR', 'CUT', 'DOG', 'EAR', 'FUN', 'GOD', 'HOT',
  'JOB', 'LEG', 'LOT', 'MAP', 'PEN', 'PET', 'SIT', 'SIX', 'TEN', 'WIN',
  'YES', 'AGO', 'AIR', 'ART', 'ASK', 'BAT', 'BIT', 'BUS', 'BUY', 'CAT',
  'CUP', 'EGG', 'FEW', 'FLY', 'GUN', 'HAT', 'HIT', 'ICE', 'KEY', 'LAW',
  'LAY', 'LIE', 'LOW', 'MIX', 'NET', 'OIL', 'PAY', 'POP', 'ROW', 'RUB',
  'SKY', 'TAX', 'TEA', 'TIE', 'TRY', 'VAN', 'WAR', 'WET', 'ZOO', 'ACE',
  'ACT', 'ADD', 'AGE', 'AID', 'AIM', 'ANT', 'ANY', 'APE', 'ARC', 'ARK',
  'ATE', 'BAY', 'BEE', 'BET', 'BIN', 'BOW', 'BUD', 'BUG', 'BUN', 'BYE',
  'CAB', 'CAN', 'CAP', 'COB', 'COD', 'COG', 'COT', 'COW', 'CRY', 'CUB',
  'CUD', 'DAM', 'DEN', 'DEW', 'DIE', 'DIG', 'DIM', 'DIP', 'DOC', 'DOT',
  'DRY', 'DUB', 'DUD', 'DUE', 'DUG', 'DUN', 'DYE', 'EEL', 'ELF', 'ELK',
  'ELM', 'ERA', 'ERR', 'EVE', 'EWE', 'FAD', 'FAN', 'FAT', 'FAX', 'FED',
  'FIG', 'FIN', 'FIR', 'FIT', 'FIX', 'FLU', 'FOB', 'FOE', 'FOG', 'FOR',
  'FOX', 'FRY', 'FUR', 'GAB', 'GAG', 'GAL', 'GAP', 'GAS', 'GAY', 'GEL',
  'GEM', 'GIG', 'GIN', 'GNU', 'GUM', 'GUT', 'GUY', 'GYM', 'HAM', 'HAY',
  'HEN', 'HEW', 'HEX', 'HEY', 'HID', 'HIP', 'HOB', 'HOG', 'HOP', 'HUB',
  'HUE', 'HUG', 'HUM', 'HUT', 'ICY', 'ILL', 'IMP', 'INK', 'INN', 'ION',
  'IRE', 'IRK', 'IVY', 'JAB', 'JAG', 'JAM', 'JAR', 'JAW', 'JAY', 'JET',
  'JIG', 'JOG', 'JOT', 'JOY', 'JUG', 'JUT', 'KEG', 'KEN', 'KID', 'KIN',
  'KIT', 'LAB', 'LAD', 'LAG', 'LAP', 'LAX', 'LEA', 'LED', 'LID', 'LIP',
  'LIT', 'LOG', 'LYE', 'MAC', 'MAD', 'MAR', 'MAT', 'MAW', 'MAX', 'MET',
  'MID', 'MOB', 'MOD', 'MOP', 'MOW', 'MUD', 'MUG', 'NAB', 'NAG', 'NAP',
  'NEW', 'NIL', 'NIT', 'NIX', 'NOB', 'NOD', 'NOR', 'NOT', 'NUB', 'NUN',
  'NUT', 'OAK', 'OAR', 'OAT', 'ODD', 'ODE', 'OFT', 'ORB', 'ORE', 'OUT',
  'OWE', 'OWL', 'PAD', 'PAL', 'PAN', 'PAP', 'PAR', 'PAT', 'PAW', 'PEA',
  'PEG', 'PEP', 'PER', 'PEW', 'PIE', 'PIG', 'PIN', 'PIT', 'PLY', 'POD',
  'POT', 'PRO', 'PRY', 'PUB', 'PUG', 'PUN', 'PUP', 'PUS', 'PUT', 'RAG',
  'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY', 'REF', 'RIB', 'RID', 'RIG',
  'RIM', 'RIP', 'ROB', 'ROD', 'ROE', 'ROT', 'RUG', 'RUM', 'RUT', 'RYE',
  'SAC', 'SAD', 'SAG', 'SAP', 'SAT', 'SHY', 'SIN', 'SIP', 'SIR', 'SIS',
  'SKI', 'SLY', 'SOB', 'SOD', 'SON', 'SOP', 'SOT', 'SOW', 'SOY', 'SPA',
  'SPY', 'STY', 'SUB', 'SUM', 'SUP', 'TAB', 'TAD', 'TAG', 'TAN', 'TAP',
  'TAR', 'TAT', 'THY', 'TIC', 'TIN', 'TIP', 'TOE', 'TON', 'TOT', 'TOW',
  'TOY', 'TUB', 'TUG', 'URN', 'VAT', 'VET', 'VIA', 'VIE', 'VOW', 'WAD',
  'WAG', 'WAX', 'WEB', 'WED', 'WEE', 'WIG', 'WIT', 'WOE', 'WOK', 'WON',
  'WOO', 'WOW', 'YAK', 'YAM', 'YAP', 'YAW', 'YEA', 'YEN', 'YET', 'YEW',
  'YIN', 'YOU', 'YOW', 'ZAP', 'ZED', 'ZEE', 'ZEN', 'ZIG', 'ZIP', 'ZIT',
  
  // 4-letter words
  'THAT', 'WITH', 'HAVE', 'THIS', 'WILL', 'YOUR', 'FROM', 'THEY', 'KNOW',
  'WANT', 'BEEN', 'GOOD', 'MUCH', 'SOME', 'TIME', 'VERY', 'WHEN', 'COME',
  'HERE', 'JUST', 'LIKE', 'LONG', 'MAKE', 'MANY', 'OVER', 'SUCH', 'TAKE',
  'THAN', 'THEM', 'WELL', 'WERE', 'WORK', 'ABLE', 'BACK', 'CALL', 'CAME',
  'EACH', 'EVEN', 'FIND', 'GIVE', 'HAND', 'HIGH', 'KEEP', 'LAST', 'LEFT',
  'LIFE', 'LIVE', 'LOOK', 'MADE', 'MOST', 'MOVE', 'MUST', 'NAME', 'NEED',
  'NEXT', 'OPEN', 'PART', 'PLAY', 'RIGHT', 'SAID', 'SAME', 'SEEM', 'SHOW',
  'SIDE', 'TELL', 'TURN', 'USED', 'WANT', 'WAYS', 'WEEK', 'WENT', 'WHAT',
  'WORD', 'YEAR', 'ALSO', 'AREA', 'AWAY', 'BEST', 'BOTH', 'CASE', 'CITY',
  'COME', 'COULD', 'DAYS', 'DOES', 'DOWN', 'FACE', 'FACT', 'FEEL', 'FELT',
  'FOUR', 'FREE', 'FULL', 'GAME', 'GAVE', 'GETS', 'GIRL', 'GOES', 'GONE',
  'HELP', 'HOME', 'HOPE', 'HOUR', 'IDEA', 'INTO', 'JOHN', 'KEEP', 'KIND',
  'KNEW', 'LATE', 'LESS', 'LINE', 'LIST', 'LONG', 'LOOK', 'LOVE', 'MAIN',
  'MAKE', 'MEAN', 'MIND', 'MORE', 'MOVE', 'NEAR', 'NEED', 'NEVER', 'NEWS',
  'NICE', 'ONLY', 'OPEN', 'OVER', 'PLAN', 'REAL', 'ROOM', 'SAID', 'SEEN',
  'SELF', 'SEND', 'SHOW', 'SIDE', 'SOON', 'SURE', 'TAKE', 'TALK', 'TELL',
  'THAN', 'THEN', 'THEY', 'TOLD', 'TOOK', 'TRUE', 'TURN', 'UPON', 'VERY',
  'WALK', 'WALL', 'WANT', 'WATER', 'WAYS', 'WEEK', 'WELL', 'WENT', 'WERE',
  'WHAT', 'WHEN', 'WILL', 'WITH', 'WORD', 'WORK', 'YEAR', 'YOUR', 'ABLE',
  'ACID', 'AGED', 'ALSO', 'AREA', 'ARMY', 'AWAY', 'BABY', 'BACK', 'BALL',
  'BAND', 'BANK', 'BASE', 'BATH', 'BEAR', 'BEAT', 'BEEN', 'BELL', 'BEST',
  'BILL', 'BIRD', 'BLOW', 'BLUE', 'BOAT', 'BODY', 'BOOK', 'BORN', 'BOTH',
  'BOYS', 'BUSY', 'CALL', 'CALM', 'CAME', 'CAMP', 'CARD', 'CARE', 'CARS',
  'CASE', 'CASH', 'CAST', 'CELL', 'CHAT', 'CITY', 'CLUB', 'COAL', 'COAT',
  'CODE', 'COLD', 'COME', 'COOL', 'COPY', 'CORN', 'COST', 'CREW', 'DARK',
  'DATA', 'DATE', 'DAYS', 'DEAD', 'DEAL', 'DEAR', 'DEEP', 'DESK', 'DIED',
  'DOES', 'DONE', 'DOOR', 'DOWN', 'DRAW', 'DREW', 'DROP', 'DRUG', 'DUAL',
  'DUCK', 'DUTY', 'EACH', 'EARN', 'EAST', 'EASY', 'EDGE', 'ELSE', 'EVEN',
  'EVER', 'EVIL', 'EXIT', 'EYES', 'FACE', 'FACT', 'FAIL', 'FAIR', 'FALL',
  'FARM', 'FAST', 'FEAR', 'FEEL', 'FEET', 'FELL', 'FELT', 'FILE', 'FILL',
  'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIVE', 'FLAG', 'FLAT',
  'FLOW', 'FOOD', 'FOOT', 'FORM', 'FORT', 'FOUR', 'FREE', 'FROM', 'FUEL',
  'FULL', 'FUND', 'GAIN', 'GAME', 'GATE', 'GAVE', 'GEAR', 'GIFT', 'GIRL',
  'GIVE', 'GLAD', 'GOAL', 'GOES', 'GOLD', 'GOLF', 'GONE', 'GOOD', 'GRAB',
  'GRAY', 'GREW', 'GRID', 'GROW', 'GUYS', 'HAIR', 'HALF', 'HALL', 'HAND',
  'HANG', 'HARD', 'HARM', 'HATE', 'HAVE', 'HEAD', 'HEAR', 'HEAT', 'HELD',
  'HELL', 'HELP', 'HERE', 'HERO', 'HIDE', 'HIGH', 'HILL', 'HINT', 'HIRE',
  'HOLD', 'HOLE', 'HOLY', 'HOME', 'HOOK', 'HOPE', 'HORN', 'HOST', 'HOUR',
  'HUGE', 'HUNG', 'HUNT', 'HURT', 'IDEA', 'INCH', 'INTO', 'IRON', 'ITEM',
  'JACK', 'JAIL', 'JAZZ', 'JOBS', 'JOIN', 'JOKE', 'JUMP', 'JUNE', 'JURY',
  'JUST', 'KEEP', 'KEPT', 'KEYS', 'KICK', 'KIDS', 'KILL', 'KIND', 'KING',
  'KISS', 'KNEE', 'KNEW', 'KNOW', 'LACK', 'LADY', 'LAID', 'LAKE', 'LAND',
  'LANE', 'LAST', 'LATE', 'LAWN', 'LAZY', 'LEAD', 'LEAF', 'LEAN', 'LEFT',
  'LEGS', 'LESS', 'LETS', 'LIFE', 'LIFT', 'LIKE', 'LINE', 'LINK', 'LION',
  'LIST', 'LIVE', 'LOAD', 'LOAN', 'LOCK', 'LONE', 'LONG', 'LOOK', 'LOOP',
  'LORD', 'LOSE', 'LOSS', 'LOST', 'LOTS', 'LOUD', 'LOVE', 'LUCK', 'MADE',
  'MAIL', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MANY', 'MAPS', 'MARK', 'MARS',
  'MASS', 'MATE', 'MATH', 'MEAL', 'MEAN', 'MEAT', 'MEET', 'MELT', 'MENU',
  'MESS', 'MICE', 'MILD', 'MILE', 'MILK', 'MILL', 'MIND', 'MINE', 'MISS',
  'MODE', 'MOOD', 'MOON', 'MORE', 'MOST', 'MOVE', 'MUCH', 'MUST', 'MYTH',
  'NAIL', 'NAME', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEWS', 'NEXT',
  'NICE', 'NINE', 'NODE', 'NONE', 'NOON', 'NORM', 'NOSE', 'NOTE', 'NOUN',
  'NUTS', 'OAKS', 'OATH', 'OBEY', 'ODDS', 'OILS', 'OKAY', 'ONCE', 'ONLY',
  'ONTO', 'OPEN', 'ORAL', 'OVER', 'OWNS', 'PACE', 'PACK', 'PAGE', 'PAID',
  'PAIN', 'PAIR', 'PALE', 'PALM', 'PARK', 'PART', 'PASS', 'PAST', 'PATH',
  'PAYS', 'PEAK', 'PEER', 'PETS', 'PICK', 'PICS', 'PILE', 'PILL', 'PINE',
  'PINK', 'PIPE', 'PLAN', 'PLAY', 'PLOT', 'PLUG', 'PLUS', 'POEM', 'POET',
  'POLE', 'POLL', 'POND', 'POOL', 'POOR', 'PORT', 'POSE', 'POST', 'POUR',
  'PRAY', 'PREP', 'PULL', 'PUMP', 'PURE', 'PUSH', 'PUTS', 'QUIT', 'QUIZ',
  'RACE', 'RACK', 'RAGE', 'RAIL', 'RAIN', 'RAKE', 'RANK', 'RARE', 'RATE',
  'RAYS', 'READ', 'REAL', 'REAR', 'RELY', 'RENT', 'REST', 'RICE', 'RICH',
  'RIDE', 'RING', 'RISE', 'RISK', 'ROAD', 'ROAR', 'ROCK', 'RODE', 'ROLE',
  'ROLL', 'ROOF', 'ROOM', 'ROOT', 'ROPE', 'ROSE', 'RUDE', 'RULE', 'RUNS',
  'RUSH', 'RUST', 'SAFE', 'SAID', 'SAIL', 'SAKE', 'SALE', 'SALT', 'SAME',
  'SAND', 'SAVE', 'SAYS', 'SCAN', 'SEAL', 'SEAT', 'SEED', 'SEEK', 'SEEM',
  'SEEN', 'SELF', 'SELL', 'SEND', 'SENT', 'SETS', 'SHED', 'SHIP', 'SHOE',
  'SHOP', 'SHOT', 'SHOW', 'SHUT', 'SICK', 'SIDE', 'SIGN', 'SILK', 'SING',
  'SINK', 'SITE', 'SITS', 'SIZE', 'SKIP', 'SKIN', 'SLIP', 'SLOW', 'SNAP',
  'SNOW', 'SOAP', 'SOCK', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOME', 'SONG',
  'SONS', 'SOON', 'SORT', 'SOUL', 'SOUP', 'SOUR', 'SPAN', 'SPIN', 'SPOT',
  'STAR', 'STAY', 'STEM', 'STEP', 'STIR', 'STOP', 'SUCH', 'SUIT', 'SUMS',
  'SURE', 'SURF', 'SWIM', 'TABS', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL',
  'TANK', 'TAPE', 'TASK', 'TAXI', 'TEAM', 'TEAR', 'TECH', 'TELL', 'TEND',
  'TENT', 'TERM', 'TEST', 'TEXT', 'THAN', 'THAT', 'THEM', 'THEN', 'THEY',
  'THIN', 'THIS', 'THUS', 'TICK', 'TIDE', 'TIED', 'TIES', 'TILE', 'TILL',
  'TIME', 'TINY', 'TIPS', 'TIRE', 'TOES', 'TOLD', 'TOLL', 'TONE', 'TOOK',
  'TOOL', 'TOPS', 'TORN', 'TOUR', 'TOWN', 'TOYS', 'TRAP', 'TREE', 'TRIM',
  'TRIP', 'TRUE', 'TUBE', 'TUNE', 'TURN', 'TWIN', 'TYPE', 'UNIT', 'UPON',
  'USED', 'USER', 'USES', 'VARY', 'VAST', 'VERY', 'VIEW', 'VINE', 'VOID',
  'VOTE', 'WADE', 'WAGE', 'WAIT', 'WAKE', 'WALK', 'WALL', 'WANT', 'WARD',
  'WARM', 'WARN', 'WARS', 'WASH', 'WAVE', 'WAYS', 'WEAK', 'WEAR', 'WEEK',
  'WELL', 'WENT', 'WERE', 'WEST', 'WHAT', 'WHEN', 'WIDE', 'WIFE', 'WILD',
  'WILL', 'WIND', 'WINE', 'WING', 'WINS', 'WIRE', 'WISE', 'WISH', 'WITH',
  'WOKE', 'WOLF', 'WOOD', 'WOOL', 'WORD', 'WORE', 'WORK', 'WORN', 'YARD',
  'YARN', 'YEAR', 'YELL', 'YOUR', 'ZERO', 'ZONE', 'ZOOM', 'ABLE', 'ACHE',
  'ACID', 'ACNE', 'ACRE', 'AGED', 'AIDE', 'AIMS', 'AIRY', 'AJAR', 'AKIN',
  'ALLY', 'ALSO', 'AMID', 'AMPS', 'ANDY', 'ANEW', 'ANTE', 'ANTI', 'ANTS',
  'ARCH', 'AREA', 'ARGS', 'ARID', 'ARMY', 'ARTS', 'ASHY', 'ATOM', 'ATOP',
  'AUNT', 'AUTO', 'AVID', 'AWAY', 'AXES', 'AXIS', 'AXLE', 'BABY', 'BACK',
  'BAIL', 'BAIT', 'BALD', 'BALL', 'BAND', 'BANK', 'BARE', 'BARK', 'BARN',
  'BASE', 'BASH', 'BATH', 'BATS', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEEN',
  'BEER', 'BELL', 'BELT', 'BEND', 'BENT', 'BEST', 'BIAS', 'BIKE', 'BILL',
  'BIND', 'BIRD', 'BITE', 'BITS', 'BLOW', 'BLUE', 'BLUR', 'BOAR', 'BOAT',
  'BODY', 'BOIL', 'BOLD', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM',
  'BOOT', 'BORE', 'BORN', 'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BOYS', 'BUCK',
  'BULB', 'BULK', 'BULL', 'BUMP', 'BURN', 'BURY', 'BUSH', 'BUSY', 'BUZZ',
  'BYTE', 'CAFE', 'CAGE', 'CAKE', 'CALL', 'CALM', 'CAME', 'CAMP', 'CANE',
  'CAPE', 'CARD', 'CARE', 'CARS', 'CART', 'CASE', 'CASH', 'CAST', 'CATS',
  'CAVE', 'CELL', 'CHAT', 'CHEF', 'CHIN', 'CHIP', 'CHOP', 'CITE', 'CITY',
  'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAW', 'CLAY', 'CLIP', 'CLUB', 'CLUE',
  'COAL', 'COAT', 'CODE', 'COIL', 'COIN', 'COLD', 'COLT', 'COMA', 'COME',
  'CONE', 'COOK', 'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN',
  'COST', 'COZY', 'CRAB', 'CREW', 'CROP', 'CROW', 'CUBE', 'CUBS', 'CUFF',
  'CULT', 'CURB', 'CURE', 'CURL', 'CUTE', 'CUTS', 'DAMP', 'DARE', 'DARK',
  'DARN', 'DART', 'DASH', 'DATA', 'DATE', 'DAWN', 'DAYS', 'DEAD', 'DEAF',
  'DEAL', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEP', 'DEER', 'DENT', 'DENY',
  'DESK', 'DIAL', 'DICE', 'DIED', 'DIET', 'DIME', 'DINE', 'DIRT', 'DISH',
  'DIVE', 'DOCK', 'DOES', 'DOGS', 'DONE', 'DOOM', 'DOOR', 'DOSE', 'DOTS',
  'DOVE', 'DOWN', 'DOZE', 'DRAG', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG',
  'DRUM', 'DUAL', 'DUCK', 'DUCT', 'DUDE', 'DUEL', 'DUES', 'DUKE', 'DULL',
  'DUMB', 'DUMP', 'DUNE', 'DUNK', 'DUSK', 'DUST', 'DUTY', 'EACH', 'EARL',
  'EARN', 'EARS', 'EASE', 'EAST', 'EASY', 'EATS', 'ECHO', 'EDGE', 'EDIT',
  'EELS', 'EGGS', 'ELSE', 'EMIT', 'ENDS', 'EPIC', 'EVEN', 'EVER', 'EVIL',
  'EXAM', 'EXIT', 'EYES', 'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR', 'FALL',
  'FAME', 'FANS', 'FARE', 'FARM', 'FAST', 'FATE', 'FATS', 'FEAR', 'FEAT',
  'FEED', 'FEEL', 'FEET', 'FELL', 'FELT', 'FERN', 'FEST', 'FEUD', 'FEWS',
  'FIAT', 'FIGS', 'FILE', 'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM',
  'FISH', 'FIST', 'FITS', 'FIVE', 'FLAG', 'FLAP', 'FLAT', 'FLAW', 'FLED',
  'FLEE', 'FLEW', 'FLEX', 'FLIP', 'FLOW', 'FLUX', 'FOAL', 'FOAM', 'FOES',
  'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORE',
  'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FOWL', 'FOXY', 'FREE', 'FROG',
  'FROM', 'FUEL', 'FULL', 'FUND', 'FURS', 'FUSE', 'FUSS', 'GAIN', 'GALE',
  'GAME', 'GANG', 'GAPS', 'GATE', 'GAVE', 'GEAR', 'GEMS', 'GETS', 'GIFT',
  'GILL', 'GIRL', 'GIVE', 'GLAD', 'GLOW', 'GLUE', 'GOAL', 'GOAT', 'GODS',
  'GOES', 'GOLD', 'GOLF', 'GONE', 'GOOD', 'GRAB', 'GRAY', 'GREW', 'GRID',
  'GRIM', 'GRIN', 'GRIP', 'GROW', 'GULF', 'GULL', 'GUNS', 'GURU', 'GUST',
  'GUYS', 'GYMS', 'HACK', 'HAIL', 'HAIR', 'HALF', 'HALL', 'HALT', 'HAND',
  'HANG', 'HARD', 'HARM', 'HART', 'HATE', 'HAVE', 'HEAD', 'HEAL', 'HEAP',
  'HEAR', 'HEAT', 'HEEL', 'HELD', 'HELL', 'HELP', 'HENS', 'HERB', 'HERD',
  'HERE', 'HERO', 'HERS', 'HIDE', 'HIGH', 'HILL', 'HINT', 'HIRE', 'HITS',
  'HIVE', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HOOD', 'HOOF', 'HOOK', 'HOOP',
  'HOPE', 'HORN', 'HOST', 'HOUR', 'HUGE', 'HULL', 'HUNG', 'HUNT', 'HURT',
  'HYMN', 'ICED', 'ICON', 'IDEA', 'IDLE', 'IDOL', 'INCH', 'INFO', 'INKS',
  'INNS', 'INTO', 'IRON', 'ISLE', 'ITEM', 'JABS', 'JACK', 'JADE', 'JAIL',
  'JAMS', 'JARS', 'JAWS', 'JAZZ', 'JEAN', 'JETS', 'JOBS', 'JOGS', 'JOIN',
  'JOKE', 'JOLT', 'JUMP', 'JUNE', 'JUNK', 'JURY', 'JUST', 'JUTE', 'KEEN',
  'KEEP', 'KEPT', 'KEYS', 'KICK', 'KIDS', 'KILL', 'KIND', 'KING', 'KISS',
  'KITE', 'KITS', 'KNEE', 'KNEW', 'KNIT', 'KNOT', 'KNOW', 'LABS', 'LACE',
  'LACK', 'LADS', 'LADY', 'LAID', 'LAKE', 'LAMB', 'LAMP', 'LAND', 'LANE',
  'LAPS', 'LARD', 'LARK', 'LAST', 'LATE', 'LAWN', 'LAWS', 'LAZY', 'LEAD',
  'LEAF', 'LEAN', 'LEAP', 'LEFT', 'LEGS', 'LEND', 'LENS', 'LENT', 'LESS',
  'LEST', 'LETS', 'LIAR', 'LICE', 'LIDS', 'LIES', 'LIFE', 'LIFT', 'LIKE',
  'LILY', 'LIMB', 'LIME', 'LINE', 'LINK', 'LINT', 'LION', 'LIPS', 'LIST',
  'LIVE', 'LOAD', 'LOAF', 'LOAN', 'LOBE', 'LOCK', 'LOFT', 'LONE', 'LONG',
  'LOOK', 'LOOP', 'LOOT', 'LORD', 'LORE', 'LOSE', 'LOSS', 'LOST', 'LOTS',
  'LOUD', 'LOVE', 'LOWS', 'LUCK', 'LUMP', 'LUNG', 'LURE', 'LUSH', 'LUST',
  'LYNX', 'MACE', 'MADE', 'MAID', 'MAIL', 'MAIN', 'MAKE', 'MALE', 'MALL',
  'MALT', 'MAMA', 'MANE', 'MANY', 'MAPS', 'MARE', 'MARK', 'MARS', 'MASK',
  'MASS', 'MAST', 'MATE', 'MATH', 'MATS', 'MAZE', 'MEAL', 'MEAN', 'MEAT',
  'MEEK', 'MEET', 'MELT', 'MEMO', 'MEND', 'MENU', 'MERE', 'MESH', 'MESS',
  'MICE', 'MILD', 'MILE', 'MILK', 'MILL', 'MIME', 'MIND', 'MINE', 'MINT',
  'MISS', 'MIST', 'MITT', 'MOAN', 'MOAT', 'MOCK', 'MODE', 'MOLD', 'MOLE',
  'MOOD', 'MOON', 'MOOR', 'MOPS', 'MORE', 'MOSS', 'MOST', 'MOTH', 'MOVE',
  'MUCH', 'MULE', 'MUMS', 'MYTH', 'NAIL', 'NAME', 'NAPS', 'NAVY', 'NEAR',
  'NEAT', 'NECK', 'NEED', 'NEST', 'NETS', 'NEWS', 'NEXT', 'NICE', 'NICK',
  'NINE', 'NODE', 'NONE', 'NOON', 'NORM', 'NOSE', 'NOTE', 'NOUN', 'NUDE',
  'NUMB', 'NUTS', 'OAKS', 'OARS', 'OATH', 'OATS', 'OBEY', 'ODDS', 'OILS',
  'OKAY', 'ONCE', 'ONLY', 'ONTO', 'OPAL', 'OPEN', 'ORAL', 'ORBS', 'ORES',
  'OVEN', 'OVER', 'OWES', 'OWLS', 'OWNS', 'PACE', 'PACK', 'PACT', 'PADS',
  'PAGE', 'PAID', 'PAIL', 'PAIN', 'PAIR', 'PALE', 'PALM', 'PANE', 'PANS',
  'PAPA', 'PARK', 'PART', 'PASS', 'PAST', 'PATH', 'PAVE', 'PAWS', 'PAYS',
  'PEAK', 'PEAR', 'PEAS', 'PEEK', 'PEEL', 'PEER', 'PEGS', 'PENS', 'PEST',
  'PETS', 'PICK', 'PICS', 'PIES', 'PIGS', 'PILE', 'PILL', 'PINE', 'PINK',
  'PINS', 'PIPE', 'PITS', 'PITY', 'PLAN', 'PLAY', 'PLOT', 'PLUG', 'PLUS',
  'POEM', 'POET', 'POLE', 'POLL', 'POLO', 'POND', 'PONY', 'POOL', 'POOR',
  'POPE', 'PORK', 'PORT', 'POSE', 'POST', 'POUR', 'PRAY', 'PREP', 'PREY',
  'PROP', 'PROS', 'PULL', 'PULP', 'PUMP', 'PUNK', 'PUNS', 'PUPS', 'PURE',
  'PUSH', 'PUTS', 'QUAD', 'QUIT', 'QUIZ', 'RACE', 'RACK', 'RAFT', 'RAGE',
  'RAGS', 'RAID', 'RAIL', 'RAIN', 'RAKE', 'RAMS', 'RANK', 'RARE', 'RATE',
  'RATS', 'RAYS', 'READ', 'REAL', 'REAP', 'REAR', 'REDS', 'REED', 'REEF',
  'RELY', 'RENT', 'REST', 'RIBS', 'RICE', 'RICH', 'RIDE', 'RIDS', 'RIGS',
  'RIMS', 'RING', 'RINK', 'RIOT', 'RIPE', 'RIPS', 'RISE', 'RISK', 'ROAD',
  'ROAM', 'ROAR', 'ROBE', 'ROCK', 'RODE', 'ROLE', 'ROLL', 'ROOF', 'ROOM',
  'ROOT', 'ROPE', 'ROSE', 'ROTS', 'RUDE', 'RUGS', 'RUIN', 'RULE', 'RUMS',
  'RUNS', 'RUSH', 'RUST', 'RUTS', 'SACK', 'SAFE', 'SAGE', 'SAID', 'SAIL',
  'SAKE', 'SALE', 'SALT', 'SAME', 'SAND', 'SANE', 'SANK', 'SAVE', 'SAWS',
  'SAYS', 'SCAN', 'SCAR', 'SEAL', 'SEAM', 'SEAS', 'SEAT', 'SECT', 'SEED',
  'SEEK', 'SEEM', 'SEEN', 'SEES', 'SELF', 'SELL', 'SEMI', 'SEND', 'SENT',
  'SETS', 'SEWN', 'SHED', 'SHIP', 'SHOE', 'SHOP', 'SHOT', 'SHOW', 'SHUT',
  'SICK', 'SIDE', 'SIGH', 'SIGN', 'SILK', 'SILL', 'SING', 'SINK', 'SIPS',
  'SIRE', 'SITE', 'SITS', 'SIZE', 'SKIP', 'SLAB', 'SLAM', 'SLAP', 'SLIM',
  'SLIP', 'SLOT', 'SLOW', 'SNAP', 'SNOW', 'SOAP', 'SOAR', 'SOCK', 'SODA',
  'SOFA', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOME', 'SONG', 'SONS', 'SOON',
  'SOOT', 'SORE', 'SORT', 'SOUL', 'SOUP', 'SOUR', 'SOWN', 'SPAN', 'SPAR',
  'SPIN', 'SPIT', 'SPOT', 'STAB', 'STAG', 'STAR', 'STAY', 'STEM', 'STEP',
  'STEW', 'STIR', 'STOP', 'STUB', 'STUD', 'STUN', 'SUCH', 'SUDS', 'SUIT',
  'SUMS', 'SUNG', 'SUNK', 'SUNS', 'SURE', 'SURF', 'SWAP', 'SWIM', 'TABS',
  'TACK', 'TACT', 'TAGS', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL', 'TAME',
  'TANK', 'TAPE', 'TAPS', 'TART', 'TASK', 'TAXI', 'TEAM', 'TEAR', 'TECH',
  'TEEN', 'TELL', 'TEND', 'TENT', 'TERM', 'TEST', 'TEXT', 'THAN', 'THAT',
  'THAW', 'THEM', 'THEN', 'THEY', 'THIN', 'THIS', 'THUS', 'TICK', 'TIDE',
  'TIDY', 'TIED', 'TIES', 'TILE', 'TILL', 'TILT', 'TIME', 'TINY', 'TIPS',
  'TIRE', 'TOAD', 'TOES', 'TOLD', 'TOLL', 'TOMB', 'TONE', 'TOOK', 'TOOL',
  'TOPS', 'TORE', 'TORN', 'TOSS', 'TOUR', 'TOWN', 'TOYS', 'TRAP', 'TREE',
  'TREK', 'TRIM', 'TRIO', 'TRIP', 'TROD', 'TRUE', 'TUBA', 'TUBE', 'TUCK',
  'TUGS', 'TUNE', 'TURN', 'TWIG', 'TWIN', 'TYPE', 'UGLY', 'UNIT', 'UPON',
  'URGE', 'USED', 'USER', 'USES', 'VAIN', 'VARY', 'VAST', 'VATS', 'VEIL',
  'VEIN', 'VERB', 'VERY', 'VEST', 'VETO', 'VETS', 'VICE', 'VIEW', 'VINE',
  'VOID', 'VOTE', 'VOWS', 'WADE', 'WAGE', 'WAGS', 'WAIT', 'WAKE', 'WALK',
  'WALL', 'WANT', 'WARD', 'WARM', 'WARN', 'WARP', 'WARS', 'WASH', 'WASP',
  'WAVE', 'WAYS', 'WEAK', 'WEAR', 'WEED', 'WEEK', 'WELL', 'WENT', 'WERE',
  'WEST', 'WHAT', 'WHEN', 'WHIP', 'WHOM', 'WIDE', 'WIFE', 'WILD', 'WILL',
  'WIND', 'WINE', 'WING', 'WINK', 'WINS', 'WIPE', 'WIRE', 'WISE', 'WISH',
  'WITH', 'WITS', 'WOKE', 'WOLF', 'WOMB', 'WOOD', 'WOOL', 'WORD', 'WORE',
  'WORK', 'WORM', 'WORN', 'WRAP', 'YARD', 'YARN', 'YAWN', 'YEAR', 'YELL',
  'YOGA', 'YOKE', 'YOUR', 'ZERO', 'ZEST', 'ZINC', 'ZONE', 'ZOOM', 'HIKE',
  'BIKE', 'LIKE', 'MIKE', 'PIKE', 'SAKE', 'WAKE', 'BAKE', 'CAKE', 'FAKE',
  'LAKE', 'MAKE', 'RAKE', 'TAKE', 'DUKE', 'LUKE', 'NUKE', 'PUKE', 'CUTE',
  'FLUE', 'GLUE', 'TRUE', 'BLUE', 'CLUE', 'CREW', 'DREW', 'FLEW', 'GREW',
  'KNEW', 'BREW', 'CHEW', 'STEW', 'VIEW', 'WHEW', 'BLEW', 'SLEW', 'SPEW',
  'THEW', 'SKEW', 'SHEW', 'PHEW', 'MEWS', 'NEWS', 'PEWS', 'SEWS', 'TEWS',
  'YEWS', 'JEWS', 'HEWS', 'DEWS', 'FEWS', 'LEWS', 'REWS', 'WEWS', 'ZEWS',
  
  // 5-letter words
  'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT',
  'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT',
  'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER',
  'AMBER', 'AMEND', 'AMONG', 'ANGER', 'ANGLE', 'ANGRY', 'APART', 'APPLE',
  'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ARMED', 'ARMOR', 'ARRAY', 'ARROW',
  'ASIDE', 'ASSET', 'ATLAS', 'AUDIO', 'AUDIT', 'AVOID', 'AWAKE', 'AWARD',
  'AWARE', 'BADLY', 'BAKER', 'BALLS', 'BANDS', 'BANKS', 'BASED', 'BASIC',
  'BATCH', 'BEACH', 'BEANS', 'BEARS', 'BEAST', 'BEGAN', 'BEGIN', 'BEING',
  'BELLY', 'BELOW', 'BENCH', 'BIKES', 'BILLS', 'BIRDS', 'BIRTH', 'BLACK',
  'BLADE', 'BLAME', 'BLANK', 'BLAST', 'BLEED', 'BLEND', 'BLESS', 'BLIND',
  'BLOCK', 'BLOOD', 'BLOOM', 'BLOWN', 'BLUES', 'BLUNT', 'BLUSH', 'BOARD',
  'BOAST', 'BOATS', 'BOBBY', 'BONDS', 'BONES', 'BONUS', 'BOOST', 'BOOTH',
  'BOOTS', 'BOUND', 'BOXES', 'BRAIN', 'BRAKE', 'BRAND', 'BRASS', 'BRAVE',
  'BREAD', 'BREAK', 'BREED', 'BRICK', 'BRIDE', 'BRIEF', 'BRING', 'BROAD',
  'BROKE', 'BROOK', 'BROWN', 'BRUSH', 'BUILD', 'BUILT', 'BUNCH', 'BURNS',
  'BURST', 'BUSES', 'BUYER', 'CABLE', 'CACHE', 'CAKES', 'CALLS', 'CAMEL',
  'CAMPS', 'CANAL', 'CANDY', 'CARDS', 'CARGO', 'CARRY', 'CARVE', 'CASES',
  'CATCH', 'CAUSE', 'CAVES', 'CEASE', 'CHAIN', 'CHAIR', 'CHAOS', 'CHARM',
  'CHART', 'CHASE', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHESS', 'CHEST',
  'CHICK', 'CHIEF', 'CHILD', 'CHINA', 'CHIPS', 'CHOSE', 'CHUNK', 'CIVIC',
  'CIVIL', 'CLAIM', 'CLAMP', 'CLASH', 'CLASS', 'CLEAN', 'CLEAR', 'CLERK',
  'CLICK', 'CLIFF', 'CLIMB', 'CLOCK', 'CLOSE', 'CLOTH', 'CLOUD', 'CLOWN',
  'CLUBS', 'CLUES', 'COACH', 'COAST', 'COATS', 'CODES', 'COINS', 'COLOR',
  'COMET', 'COMIC', 'CORAL', 'CORPS', 'COSTS', 'COUCH', 'COUGH', 'COULD',
  'COUNT', 'COURT', 'COVER', 'CRACK', 'CRAFT', 'CRANE', 'CRASH', 'CRAZY',
  'CREAM', 'CREEK', 'CRIME', 'CRISP', 'CROPS', 'CROSS', 'CROWD', 'CROWN',
  'CRUDE', 'CRUEL', 'CRUSH', 'CURVE', 'CYCLE', 'DAILY', 'DAIRY', 'DAISY',
  'DANCE', 'DATED', 'DATES', 'DEALT', 'DEATH', 'DEBIT', 'DEBUG', 'DEBUT',
  'DELAY', 'DELTA', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DEVIL', 'DIARY',
  'DIGIT', 'DIRTY', 'DISCO', 'DITCH', 'DIVER', 'DIZZY', 'DODGE', 'DOING',
  'DOLLS', 'DONOR', 'DOORS', 'DOUBT', 'DOUGH', 'DOZEN', 'DRAFT', 'DRAIN',
  'DRAMA', 'DRANK', 'DRAWN', 'DREAM', 'DRESS', 'DRIED', 'DRILL', 'DRINK',
  'DRIVE', 'DROVE', 'DRUGS', 'DRUMS', 'DRUNK', 'DUCKS', 'DUMMY', 'DUMPS',
  'DUSTY', 'DUTCH', 'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EIGHT',
  'ELBOW', 'ELDER', 'ELECT', 'ELITE', 'EMPTY', 'ENEMY', 'ENJOY', 'ENTER',
  'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY', 'EXACT', 'EXAMS', 'EXCEL',
  'EXIST', 'EXTRA', 'FABLE', 'FACED', 'FACTS', 'FADED', 'FAILS', 'FAIRY',
  'FAITH', 'FALSE', 'FANCY', 'FARMS', 'FATAL', 'FAULT', 'FAVOR', 'FEARS',
  'FEAST', 'FENCE', 'FERRY', 'FETCH', 'FEVER', 'FEWER', 'FIBER', 'FIELD',
  'FIFTH', 'FIFTY', 'FIGHT', 'FILED', 'FILLS', 'FILMS', 'FINAL', 'FINDS',
  'FINED', 'FINES', 'FIRED', 'FIRES', 'FIRMS', 'FIRST', 'FIXED', 'FIXES',
  'FLAGS', 'FLAME', 'FLAPS', 'FLASH', 'FLASK', 'FLESH', 'FLIES', 'FLOAT',
  'FLOCK', 'FLOOD', 'FLOOR', 'FLOUR', 'FLOWS', 'FLUID', 'FLUSH', 'FOCAL',
  'FOCUS', 'FOLKS', 'FONTS', 'FOODS', 'FORCE', 'FORMS', 'FORTH', 'FORTY',
  'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRIED', 'FRONT',
  'FROST', 'FRUIT', 'FULLY', 'FUNDS', 'FUNNY', 'GAMES', 'GATES', 'GEARS',
  'GENES', 'GHOST', 'GIANT', 'GIFTS', 'GIRLS', 'GIVEN', 'GIVES', 'GLASS',
  'GLOBE', 'GLORY', 'GLOVE', 'GOALS', 'GOATS', 'GOING', 'GOODS', 'GRACE',
  'GRADE', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS',
  'GRAVE', 'GREAT', 'GREED', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIND',
  'GRIPS', 'GROSS', 'GROUP', 'GROWN', 'GROWS', 'GUARD', 'GUESS', 'GUEST',
  'GUIDE', 'GUILD', 'GUILT', 'HABIT', 'HALLS', 'HANDS', 'HANDY', 'HAPPY',
  'HARSH', 'HASTE', 'HASTY', 'HATED', 'HEADS', 'HEALS', 'HEARD', 'HEART',
  'HEAVY', 'HEDGE', 'HEELS', 'HELLO', 'HELPS', 'HENCE', 'HERBS', 'HILLS',
  'HINTS', 'HIRED', 'HOBBY', 'HOLDS', 'HOLES', 'HOLLY', 'HOMES', 'HONEY',
  'HONOR', 'HOOKS', 'HOPED', 'HOPES', 'HORNS', 'HORSE', 'HOTEL', 'HOURS',
  'HOUSE', 'HUMAN', 'HUMOR', 'HURRY', 'HURTS', 'IDEAL', 'IDEAS', 'IMAGE',
  'IMPLY', 'INDEX', 'INNER', 'INPUT', 'INTRO', 'ISSUE', 'ITEMS', 'JEANS',
  'JEWEL', 'JOINS', 'JOINT', 'JOKES', 'JUDGE', 'JUICE', 'JUMPS', 'KEEPS',
  'KILLS', 'KINDS', 'KINGS', 'KNIFE', 'KNOCK', 'KNOTS', 'KNOWN', 'KNOWS',
  'LABEL', 'LABOR', 'LACKS', 'LAKES', 'LAMPS', 'LANDS', 'LANES', 'LARGE',
  'LASER', 'LATER', 'LAUGH', 'LAYER', 'LEADS', 'LEARN', 'LEASE', 'LEAST',
  'LEAVE', 'LEGAL', 'LEMON', 'LEVEL', 'LEVER', 'LIGHT', 'LIKED', 'LIKES',
  'LIMIT', 'LINED', 'LINES', 'LINKS', 'LIONS', 'LISTS', 'LIVED', 'LIVER',
  'LIVES', 'LOANS', 'LOCAL', 'LOCKS', 'LODGE', 'LOGIC', 'LOOKS', 'LOOPS',
  'LOOSE', 'LORDS', 'LOSES', 'LOVED', 'LOVER', 'LOVES', 'LOWER', 'LOYAL',
  'LUCKY', 'LUNCH', 'LUNGS', 'LYING', 'MAGIC', 'MAJOR', 'MAKER', 'MAKES',
  'MALES', 'MARCH', 'MARKS', 'MARRY', 'MATCH', 'MATES', 'MAYBE', 'MAYOR',
  'MEALS', 'MEANS', 'MEANT', 'MEATS', 'MEDAL', 'MEDIA', 'MEETS', 'MELON',
  'MELTS', 'MENUS', 'MERCY', 'MERGE', 'MERIT', 'MERRY', 'METAL', 'METER',
  'METRO', 'MICRO', 'MIGHT', 'MILES', 'MINDS', 'MINES', 'MINOR', 'MINUS',
  'MIXED', 'MIXES', 'MODEL', 'MODES', 'MONEY', 'MONKS', 'MONTH', 'MOODS',
  'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVED', 'MOVES', 'MOVIE',
  'MUSIC', 'MYTHS', 'NAKED', 'NAMED', 'NAMES', 'NASTY', 'NEEDS', 'NERVE',
  'NEVER', 'NEWER', 'NEWLY', 'NIGHT', 'NINTH', 'NOBLE', 'NODES', 'NOISE',
  'NORTH', 'NOTED', 'NOTES', 'NOVEL', 'NURSE', 'OATHS', 'OCCUR', 'OCEAN',
  'OFFER', 'OFTEN', 'OLDER', 'OLIVE', 'OPENS', 'OPERA', 'ORDER', 'ORGAN',
  'OTHER', 'OUGHT', 'OUTER', 'OWNED', 'OWNER', 'PAGES', 'PAINS', 'PAINT',
  'PAIRS', 'PANEL', 'PANIC', 'PAPER', 'PARKS', 'PARTS', 'PARTY', 'PASTA',
  'PASTE', 'PATCH', 'PATHS', 'PAUSE', 'PEACE', 'PEACH', 'PEAKS', 'PEARL',
  'PENNY', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PICKS', 'PIECE', 'PILOT',
  'PITCH', 'PIZZA', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'PLAYS',
  'PLAZA', 'PLOTS', 'POEMS', 'POETS', 'POINT', 'POLES', 'POLLS', 'POOLS',
  'PORCH', 'PORTS', 'POSED', 'POSTS', 'POUND', 'POWER', 'PRESS', 'PRICE',
  'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROPS', 'PROUD',
  'PROVE', 'PULLS', 'PULSE', 'PUMPS', 'PUNCH', 'PUPIL', 'PURSE', 'QUEEN',
  'QUERY', 'QUEST', 'QUICK', 'QUIET', 'QUITE', 'QUOTE', 'RADIO', 'RAISE',
  'RANGE', 'RANKS', 'RAPID', 'RATES', 'RATIO', 'REACH', 'READS', 'READY',
  'REALM', 'REBEL', 'REFER', 'RELAX', 'RELAY', 'REPLY', 'RESET', 'RIGHT',
  'RINGS', 'RISES', 'RISKS', 'RIVAL', 'RIVER', 'ROADS', 'ROBOT', 'ROCKS',
  'ROLES', 'ROLLS', 'ROMAN', 'ROOMS', 'ROOTS', 'ROPES', 'ROSES', 'ROUGH',
  'ROUND', 'ROUTE', 'ROYAL', 'RUGBY', 'RULES', 'RURAL', 'SADLY', 'SAFER',
  'SAINT', 'SALAD', 'SALES', 'SALON', 'SANDY', 'SAUCE', 'SAVED', 'SAVES',
  'SCALE', 'SCARE', 'SCENE', 'SCOPE', 'SCORE', 'SCOTS', 'SCOUT', 'SCRAP',
  'SCREW', 'SEATS', 'SEEDS', 'SEEKS', 'SEEMS', 'SELLS', 'SENSE', 'SERVE',
  'SETUP', 'SEVEN', 'SHADE', 'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE',
  'SHARK', 'SHARP', 'SHEEP', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE',
  'SHIPS', 'SHIRT', 'SHOCK', 'SHOES', 'SHOOT', 'SHOPS', 'SHORE', 'SHORT',
  'SHOTS', 'SHOWN', 'SHOWS', 'SIDES', 'SIGHT', 'SIGNS', 'SILLY', 'SINCE',
  'SIXTH', 'SIXTY', 'SIZED', 'SIZES', 'SKILL', 'SLEEP', 'SLIDE', 'SLOPE',
  'SLOTS', 'SMALL', 'SMART', 'SMILE', 'SMOKE', 'SNAKE', 'SNAPS', 'SOCKS',
  'SOLAR', 'SOLID', 'SOLVE', 'SONGS', 'SORRY', 'SORTS', 'SOULS', 'SOUND',
  'SOUTH', 'SPACE', 'SPARE', 'SPARK', 'SPEAK', 'SPEED', 'SPELL', 'SPEND',
  'SPENT', 'SPINE', 'SPLIT', 'SPOKE', 'SPORT', 'SPOTS', 'SPRAY', 'SQUAD',
  'STACK', 'STAFF', 'STAGE', 'STAIR', 'STAKE', 'STAMP', 'STAND', 'STARS',
  'START', 'STATE', 'STAYS', 'STEAL', 'STEAM', 'STEEL', 'STEEP', 'STEER',
  'STEPS', 'STICK', 'STILL', 'STOCK', 'STONE', 'STOOD', 'STOPS', 'STORE',
  'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR',
  'SUITE', 'SUITS', 'SUPER', 'SWEET', 'SWEPT', 'SWIFT', 'SWING', 'SWISS',
  'TABLE', 'TAKEN', 'TAKES', 'TALES', 'TALKS', 'TANKS', 'TAPES', 'TASKS',
  'TASTE', 'TAXES', 'TEACH', 'TEAMS', 'TEARS', 'TEENS', 'TEETH', 'TELLS',
  'TENDS', 'TENTS', 'TERMS', 'TESTS', 'TEXTS', 'THANK', 'THEFT', 'THEIR',
  'THEME', 'THERE', 'THESE', 'THICK', 'THING', 'THINK', 'THIRD', 'THOSE',
  'THREE', 'THREW', 'THROW', 'THUMB', 'TIGER', 'TIGHT', 'TILES', 'TIMES',
  'TIRED', 'TITLE', 'TODAY', 'TOKEN', 'TOOLS', 'TOOTH', 'TOPIC', 'TOTAL',
  'TOUCH', 'TOUGH', 'TOURS', 'TOWER', 'TOWNS', 'TRACK', 'TRADE', 'TRAIL',
  'TRAIN', 'TRAIT', 'TRASH', 'TREAT', 'TREES', 'TREND', 'TRIAL', 'TRIBE',
  'TRICK', 'TRIED', 'TRIES', 'TRIPS', 'TRUCK', 'TRULY', 'TRUNK', 'TRUST',
  'TRUTH', 'TUBES', 'TUNES', 'TURNS', 'TWICE', 'TWINS', 'TWIST', 'TYPED',
  'TYPES', 'ULTRA', 'UNCLE', 'UNDER', 'UNION', 'UNITS', 'UNITY', 'UNTIL',
  'UPPER', 'UPSET', 'URBAN', 'URGED', 'USAGE', 'USERS', 'USING', 'USUAL',
  'VALUE', 'VIDEO', 'VIEWS', 'VIRUS', 'VISIT', 'VITAL', 'VOCAL', 'VOICE',
  'VOTES', 'WAGES', 'WAIST', 'WAITS', 'WAKES', 'WALKS', 'WALLS', 'WANTS',
  'WARDS', 'WARMS', 'WARNS', 'WASTE', 'WATCH', 'WATER', 'WAVES', 'WEARY',
  'WEEKS', 'WEIRD', 'WELLS', 'WELSH', 'WHEAT', 'WHEEL', 'WHERE', 'WHICH',
  'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WIDER', 'WIDOW', 'WIDTH', 'WINDS',
  'WINES', 'WINGS', 'WIPES', 'WIRED', 'WIRES', 'WITCH', 'WIVES', 'WOMAN',
  'WOMEN', 'WOODS', 'WORDS', 'WORKS', 'WORLD', 'WORRY', 'WORSE', 'WORST',
  'WORTH', 'WOULD', 'WRIST', 'WRITE', 'WRONG', 'WROTE', 'YARDS', 'YEARS',
  'YIELD', 'YOUNG', 'YOURS', 'YOUTH', 'ZONES', 'HIKED', 'HIKES', 'BIKED',
  'BIKES', 'LIKED', 'LIKES', 'MIKED', 'MIKES', 'PIKED', 'PIKES', 'SAKED',
  'SAKES', 'WAKED', 'WAKES', 'BAKED', 'BAKES', 'CAKED', 'CAKES', 'FAKED',
  'FAKES', 'LAKED', 'LAKES', 'MAKED', 'MAKES', 'RAKED', 'RAKES', 'TAKED',
  'TAKES', 'DUKED', 'DUKES', 'LUKED', 'LUKES', 'NUKED', 'NUKES', 'PUKED',
  'PUKES', 'CUTED', 'CUTES', 'FLUED', 'FLUES', 'GLUED', 'GLUES', 'TRUED',
  'TRUES', 'BLUED', 'BLUES', 'CLUED', 'CLUES', 'CREWED', 'CREWS', 'DREWED',
  'DREWS', 'FLEWED', 'FLEWS', 'GREWED', 'GREWS', 'KNEWED', 'KNEWS', 'BREWED',
  'BREWS', 'CHEWED', 'CHEWS', 'STEWED', 'STEWS', 'VIEWED', 'VIEWS', 'WHEWED',
  'WHEWS', 'BLEWED', 'BLEWS', 'SLEWED', 'SLEWS', 'SPEWED', 'SPEWS', 'THEWED',
  'THEWS', 'SKEWED', 'SKEWS', 'SHEWED', 'SHEWS', 'PHEWED', 'PHEWS', 'MEWSED',
  'MEWSES', 'NEWSED', 'NEWSES', 'PEWSED', 'PEWSES', 'SEWSED', 'SEWSES',
  'TEWSED', 'TEWSES', 'YEWSED', 'YEWSES', 'JEWSED', 'JEWSES', 'HEWSED',
  'HEWSES', 'DEWSED', 'DEWSES', 'FEWSED', 'FEWSES', 'LEWSED', 'LEWSES',
  'REWSED', 'REWSES', 'WEWSED', 'WEWSES', 'ZEWSED', 'ZEWSES',
  
  // 6-letter words
  'ABOARD', 'ABROAD', 'ABSENT', 'ABSORB', 'ACCEPT', 'ACCESS', 'ACCORD',
  'ACROSS', 'ACTION', 'ACTIVE', 'ACTUAL', 'ADJUST', 'ADVICE', 'ADVISE',
  'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AGENCY', 'AGENDA', 'AGREED',
  'AGREES', 'AIMING', 'ALMOST', 'ALPINE', 'ALWAYS', 'AMOUNT', 'ANCHOR',
  'ANGELS', 'ANIMAL', 'ANNUAL', 'ANSWER', 'ANYONE', 'ANYWAY', 'APPEAL',
  'APPEAR', 'APPLES', 'ARCADE', 'ARCHER', 'ARCTIC', 'ARGUED', 'ARGUES',
  'AROUND', 'ARREST', 'ARRIVE', 'ARTIST', 'ASKING', 'ASPECT', 'ASSESS',
  'ASSIST', 'ASSUME', 'ASSURE', 'ASYLUM', 'ATOMIC', 'ATTACH', 'ATTACK',
  'ATTEND', 'AUGUST', 'AUTHOR', 'AUTUMN', 'AVENUE', 'AWARDS', 'BABIES',
  'BACKED', 'BACKUP', 'BADGES', 'BALLET', 'BANANA', 'BANKER', 'BANNER',
  'BARELY', 'BARREL', 'BATTLE', 'BEACON', 'BEAUTY', 'BECAME', 'BECOME',
  'BEFORE', 'BEHALF', 'BEHAVE', 'BEHIND', 'BELIEF', 'BELONG', 'BESIDE',
  'BETTER', 'BEYOND', 'BINARY', 'BISHOP', 'BITTER', 'BLANKS', 'BLOCKS',
  'BLONDE', 'BLOODY', 'BOARDS', 'BODIES', 'BOILED', 'BOMBER', 'BORDER',
  'BOTTLE', 'BOTTOM', 'BOUGHT', 'BOUNCE', 'BOXING', 'BRANCH', 'BRANDS',
  'BREATH', 'BRIDGE', 'BRIGHT', 'BRINGS', 'BROKEN', 'BRONZE', 'BROWSE',
  'BUCKET', 'BUDGET', 'BUFFER', 'BUILDS', 'BUNDLE', 'BURDEN', 'BUREAU',
  'BURIED', 'BURNED', 'BUTTER', 'BUTTON', 'BUYERS', 'BUYING', 'CABLES',
  'CAMERA', 'CAMPUS', 'CANCER', 'CANDLE', 'CANNOT', 'CANVAS', 'CARBON',
  'CAREER', 'CARING', 'CARPET', 'CASTLE', 'CASUAL', 'CAUGHT', 'CAUSED',
  'CAUSES', 'CAVITY', 'CEASED', 'CENSUS', 'CENTER', 'CENTRE', 'CEREAL',
  'CHAINS', 'CHAIRS', 'CHANCE', 'CHANGE', 'CHAPEL', 'CHARGE', 'CHARTS',
  'CHEESE', 'CHERRY', 'CHOICE', 'CHOOSE', 'CHOSEN', 'CHROME', 'CHURCH',
  'CIRCLE', 'CIRCUS', 'CITIES', 'CLAIMS', 'CLAUSE', 'CLIENT', 'CLIMAX',
  'CLINIC', 'CLOSED', 'CLOSER', 'CLOSES', 'CLOUDS', 'CLUMSY', 'COARSE',
  'COATED', 'COFFEE', 'COLLAR', 'COLONY', 'COLORS', 'COLUMN', 'COMBAT',
  'COMEDY', 'COMING', 'COMMIT', 'COMMON', 'COMPLY', 'COPPER', 'CORNER',
  'COSMIC', 'COTTON', 'COUNTY', 'COUPLE', 'COURSE', 'COUSIN', 'COVERS',
  'CRAFTS', 'CREATE', 'CREDIT', 'CRISIS', 'CRITIC', 'CROWDS', 'CRUISE',
  'CRYING', 'CUSTOM', 'CYCLES', 'DAMAGE', 'DANCER', 'DANGER', 'DARKER',
  'DATING', 'DEALER', 'DEBATE', 'DEBRIS', 'DECADE', 'DECENT', 'DECIDE',
  'DEFEAT', 'DEFEND', 'DEFINE', 'DEGREE', 'DEMAND', 'DENTAL', 'DEPEND',
  'DEPUTY', 'DERIVE', 'DESERT', 'DESIGN', 'DESIRE', 'DETAIL', 'DETECT',
  'DEVICE', 'DIALOG', 'DIFFER', 'DIGEST', 'DINING', 'DIRECT', 'DIVIDE',
  'DOCTOR', 'DOMAIN', 'DONATE', 'DOUBLE', 'DRAGON', 'DRAWER', 'DREAMS',
  'DRINKS', 'DRIVER', 'DRIVES', 'DURING', 'DUTIES', 'EAGLES', 'EARNED',
  'EASIER', 'EASILY', 'EATING', 'EDITOR', 'EFFECT', 'EFFORT', 'EIGHTH',
  'EITHER', 'ELEVEN', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENDING', 'ENERGY',
  'ENGINE', 'ENOUGH', 'ENSURE', 'ENTIRE', 'ENTITY', 'EQUALS', 'ESCAPE',
  'ESTATE', 'ETHICS', 'ETHNIC', 'EVENTS', 'EXCEPT', 'EXCUSE', 'EXPAND',
  'EXPECT', 'EXPERT', 'EXPORT', 'EXTEND', 'EXTENT', 'FABRIC', 'FACIAL',
  'FACING', 'FACTOR', 'FAILED', 'FAIRLY', 'FALLEN', 'FAMILY', 'FAMOUS',
  'FARMER', 'FATHER', 'FAULTY', 'FEARED', 'FEEDER', 'FELLOW', 'FEMALE',
  'FIELDS', 'FIERCE', 'FIGURE', 'FILLED', 'FILTER', 'FINGER', 'FINISH',
  'FIRING', 'FIRMLY', 'FISCAL', 'FITTED', 'FIXING', 'FLIGHT', 'FLOORS',
  'FLOWER', 'FLYING', 'FOLDER', 'FOLLOW', 'FORCED', 'FORCES', 'FOREST',
  'FORGET', 'FORMAT', 'FORMER', 'FOUGHT', 'FOURTH', 'FRAMES', 'FRANCE',
  'FREELY', 'FRENCH', 'FRIDAY', 'FRIEND', 'FROZEN', 'FRUITS', 'FUNDED',
  'FUSION', 'FUTURE', 'GALAXY', 'GARAGE', 'GARDEN', 'GARLIC', 'GATHER',
  'GENDER', 'GENTLE', 'GERMAN', 'GIANTS', 'GIFTED', 'GIVING', 'GLOBAL',
  'GOLDEN', 'GOSPEL', 'GOTTEN', 'GRADES', 'GRAINS', 'GRANTS', 'GRAPES',
  'GRAPHS', 'GRAVEL', 'GREENS', 'GREETS', 'GROUND', 'GROUPS', 'GROWTH',
  'GUARDS', 'GUESTS', 'GUIDED', 'GUIDES', 'GUILTY', 'GUITAR', 'HABITS',
  'HAMMER', 'HANDED', 'HANDLE', 'HAPPEN', 'HARBOR', 'HARDLY', 'HATRED',
  'HAVING', 'HEADED', 'HEADER', 'HEALTH', 'HEARTS', 'HEATED', 'HEAVEN',
  'HEIGHT', 'HELPED', 'HELPER', 'HEROES', 'HIDDEN', 'HIGHER', 'HIGHLY',
  'HIKING', 'HIRING', 'HOCKEY', 'HOLDER', 'HONEST', 'HOPING', 'HORSES',
  'HOTELS', 'HOUSED', 'HOUSES', 'HUMANS', 'HUNGER', 'HUNTER', 'HURDLE',
  'HYBRID', 'IMAGES', 'IMMUNE', 'IMPACT', 'IMPORT', 'IMPOSE', 'INCOME',
  'INDEED', 'INDOOR', 'INFANT', 'INFORM', 'INJECT', 'INJURY', 'INLINE',
  'INPUTS', 'INSECT', 'INSERT', 'INSIDE', 'INSIST', 'INSURE', 'INTAKE',
  'INTEND', 'INTENT', 'INVEST', 'INVITE', 'ISLAND', 'ISSUED', 'ISSUES',
  'ITSELF', 'JACKET', 'JOINED', 'JOINTS', 'JUNGLE', 'JUNIOR', 'KEEPER',
  'KIDNEY', 'KILLED', 'KILLER', 'KINDLY', 'KNIGHT', 'LABELS', 'LADDER',
  'LADIES', 'LANDED', 'LAPTOP', 'LARGER', 'LASTED', 'LATELY', 'LATEST',
  'LATTER', 'LAUNCH', 'LAWYER', 'LAYERS', 'LEADER', 'LEAGUE', 'LEARNS',
  'LEAVES', 'LEGACY', 'LEGEND', 'LENGTH', 'LESSON', 'LETTER', 'LEVELS',
  'LIABLE', 'LIGHTS', 'LIKELY', 'LIMITS', 'LINEAR', 'LINKED', 'LIQUID',
  'LISTEN', 'LITTLE', 'LIVING', 'LOADED', 'LOADER', 'LOCATE', 'LOCKED',
  'LOCKER', 'LONDON', 'LONGER', 'LOOKED', 'LOSING', 'LOVELY', 'LOVERS',
  'LOVING', 'LUMBER', 'LUXURY', 'LYRICS', 'MAINLY', 'MAKING', 'MANAGE',
  'MANNER', 'MANUAL', 'MARBLE', 'MARGIN', 'MARINE', 'MARKED', 'MARKER',
  'MARKET', 'MARKUP', 'MASTER', 'MATTER', 'MATURE', 'MEADOW', 'MEDALS',
  'MEDIUM', 'MEMBER', 'MEMORY', 'MENTAL', 'MENTOR', 'MERELY', 'MERGER',
  'METALS', 'METHOD', 'METRIC', 'MIDDLE', 'MILLER', 'MINING', 'MINUTE',
  'MIRROR', 'MISSED', 'MISSES', 'MOBILE', 'MODELS', 'MODERN', 'MODEST',
  'MODULE', 'MOMENT', 'MONDAY', 'MONKEY', 'MONTHS', 'MORALS', 'MOSTLY',
  'MOTHER', 'MOTION', 'MOVING', 'MURDER', 'MUSCLE', 'MUSEUM', 'MUTUAL',
  'MYSELF', 'NATION', 'NATIVE', 'NATURE', 'NEARBY', 'NEARLY', 'NEEDED',
  'NEEDLE', 'NEPHEW', 'NERVES', 'NESTED', 'NEURAL', 'NEWEST', 'NICELY',
  'NIGHTS', 'NOBODY', 'NORMAL', 'NOTICE', 'NOTION', 'NOVELS', 'NUMBER',
  'NURSES', 'OBJECT', 'OBTAIN', 'OCCUPY', 'OCCURS', 'OCEANS', 'OFFERS',
  'OFFICE', 'OFFSET', 'ONLINE', 'OPENED', 'OPENER', 'OPTION', 'ORANGE',
  'ORDERS', 'ORGANS', 'ORIGIN', 'OTHERS', 'OUTPUT', 'OUTSET', 'OWNERS',
  'OWNING', 'OXYGEN', 'PACKED', 'PACKET', 'PALACE', 'PANELS', 'PAPERS',
  'PARADE', 'PARENT', 'PARISH', 'PARKED', 'PARTLY', 'PASSED', 'PASSES',
  'PASTOR', 'PATENT', 'PATROL', 'PAYING', 'PENCIL', 'PEOPLE', 'PEPPER',
  'PERIOD', 'PERMIT', 'PERSON', 'PHONES', 'PHOTOS', 'PHRASE', 'PICKED',
  'PICKLE', 'PICNIC', 'PIECES', 'PILOTS', 'PLACED', 'PLACES', 'PLAINS',
  'PLANES', 'PLANET', 'PLANTS', 'PLATES', 'PLAYED', 'PLAYER', 'PLEASE',
  'PLENTY', 'POCKET', 'POETRY', 'POINTS', 'POLICE', 'POLICY', 'POLISH',
  'POLLEN', 'POORLY', 'PORTAL', 'POSTER', 'POTATO', 'POUNDS', 'POWDER',
  'POWERS', 'PRAISE', 'PRAYER', 'PREFER', 'PREFIX', 'PRETTY', 'PRICES',
  'PRIEST', 'PRINCE', 'PRINTS', 'PRISON', 'PRIZES', 'PROFIT', 'PROMPT',
  'PROPER', 'PROVEN', 'PROVES', 'PUBLIC', 'PULLED', 'PURPLE', 'PUSHED',
  'PUSHES', 'PUZZLE', 'QUARTZ', 'QUEENS', 'QUOTES', 'RABBIT', 'RACING',
  'RADIUS', 'RAISED', 'RAISES', 'RANDOM', 'RANGES', 'RARELY', 'RATHER',
  'RATING', 'READER', 'REALLY', 'REASON', 'REBELS', 'RECALL', 'RECENT',
  'RECORD', 'REDUCE', 'REFERS', 'REFORM', 'REFUSE', 'REGARD', 'REGION',
  'REJECT', 'RELATE', 'RELIEF', 'REMAIN', 'REMARK', 'REMOTE', 'REMOVE',
  'REPAIR', 'REPEAT', 'REPLAY', 'REPORT', 'RESCUE', 'RESENT', 'RESIST',
  'RESORT', 'RESULT', 'RESUME', 'RETAIL', 'RETIRE', 'RETURN', 'REVEAL',
  'REVIEW', 'REWARD', 'RHYTHM', 'RIBBON', 'RIDING', 'RIGHTS', 'RISING',
  'RITUAL', 'RIVERS', 'ROBOTS', 'ROCKET', 'ROLLED', 'ROLLER', 'ROMANS',
  'ROOTED', 'ROTATE', 'ROUTES', 'RUBBER', 'RULING', 'RUMORS', 'RUNNER',
  'RUSHED', 'RUSHES', 'SACRED', 'SADDLE', 'SAFELY', 'SAFETY', 'SALARY',
  'SALMON', 'SAMPLE', 'SAVING', 'SAYING', 'SCALES', 'SCARED', 'SCENES',
  'SCHEME', 'SCHOOL', 'SCORES', 'SCREEN', 'SCRIPT', 'SCROLL', 'SEALED',
  'SEARCH', 'SEASON', 'SEATED', 'SECOND', 'SECRET', 'SECTOR', 'SECURE',
  'SEEING', 'SEEMED', 'SELLER', 'SENATE', 'SENIOR', 'SENSES', 'SERIES',
  'SERVED', 'SERVER', 'SERVES', 'SETTLE', 'SEVERE', 'SHADOW', 'SHADES',
  'SHAKEN', 'SHAKER', 'SHAKES', 'SHAPES', 'SHARED', 'SHARES', 'SHARKS',
  'SHEETS', 'SHELLS', 'SHIELD', 'SHIFTS', 'SHINES', 'SHIRTS', 'SHOCKS',
  'SHOOTS', 'SHORTS', 'SHOULD', 'SHOWER', 'SHOWED', 'SHRINE', 'SIGHTS',
  'SIGNAL', 'SIGNED', 'SILENT', 'SILVER', 'SIMPLE', 'SIMPLY', 'SINGER',
  'SINGLE', 'SISTER', 'SKILLS', 'SLIDES', 'SLIGHT', 'SLOWLY', 'SMILES',
  'SMOOTH', 'SNAKES', 'SOCCER', 'SOCIAL', 'SOCKET', 'SODIUM', 'SOFTER',
  'SOLELY', 'SOLVED', 'SOLVER', 'SOLVES', 'SOUNDS', 'SOURCE', 'SPACES',
  'SPEAKS', 'SPEECH', 'SPEEDS', 'SPHERE', 'SPIDER', 'SPIRAL', 'SPIRIT',
  'SPLITS', 'SPOKEN', 'SPORTS', 'SPREAD', 'SPRING', 'SQUARE', 'STABLE',
  'STAGES', 'STAIRS', 'STAMPS', 'STANDS', 'STARTS', 'STATED', 'STATES',
  'STATIC', 'STATUE', 'STATUS', 'STAYED', 'STEADY', 'STEALS', 'STEAMS',
  'STEELS', 'STEERS', 'STICKS', 'STOCKS', 'STOLEN', 'STONES', 'STORED',
  'STORES', 'STORMS', 'STRAIN', 'STRAND', 'STREAM', 'STREET', 'STRESS',
  'STRICT', 'STRIKE', 'STRING', 'STRIPS', 'STROKE', 'STRONG', 'STRUCK',
  'STUDIO', 'STUPID', 'STYLES', 'SUBMIT', 'SUBWAY', 'SUDDEN', 'SUFFER',
  'SUGARS', 'SUMMER', 'SUMMIT', 'SUNDAY', 'SUNSET', 'SUPPLY', 'SURELY',
  'SURVEY', 'SWITCH', 'SYMBOL', 'SYNTAX', 'SYSTEM', 'TABLES', 'TABLET',
  'TACKLE', 'TAKING', 'TALENT', 'TALKED', 'TARGET', 'TAUGHT', 'TEMPLE',
  'TENANT', 'TENNIS', 'TENSOR', 'TESTED', 'THANKS', 'THEORY', 'THINGS',
  'THINKS', 'THIRTY', 'THOUGH', 'THREAD', 'THREAT', 'THRONE', 'THROWN',
  'THROWS', 'THUMBS', 'TICKET', 'TIGERS', 'TIMBER', 'TIMING', 'TISSUE',
  'TITLES', 'TOILET', 'TOMATO', 'TONGUE', 'TOPICS', 'TOWARD', 'TOWERS',
  'TRACKS', 'TRADES', 'TRAILS', 'TRAINS', 'TRAITS', 'TRAVEL', 'TREATS',
  'TRENDS', 'TRIALS', 'TRIBES', 'TRICKS', 'TRIPLE', 'TROOPS', 'TRUCKS',
  'TRUSTS', 'TRYING', 'TUNNEL', 'TURNED', 'TWELVE', 'TWENTY', 'TYPING',
  'UNABLE', 'UNIQUE', 'UNITED', 'UNLESS', 'UNLIKE', 'UNLOCK', 'UNUSED',
  'UPDATE', 'UPLOAD', 'UPWARD', 'URGENT', 'USABLE', 'USEFUL', 'VALUES',
  'VARIED', 'VARIES', 'VECTOR', 'VENDOR', 'VENUES', 'VERSUS', 'VESSEL',
  'VICTIM', 'VIDEOS', 'VIEWED', 'VIEWER', 'VIOLET', 'VIRGIN', 'VIRTUE',
  'VISION', 'VISUAL', 'VOICES', 'VOLUME', 'VOTERS', 'VOTING', 'WAITED',
  'WALKER', 'WALKED', 'WALLET', 'WANTED', 'WARMER', 'WARNED', 'WASHED',
  'WASHES', 'WEALTH', 'WEAPON', 'WEEKLY', 'WEIGHT', 'WHEELS', 'WIDELY',
  'WIDGET', 'WINDOW', 'WINNER', 'WINTER', 'WISDOM', 'WISHES', 'WITHIN',
  'WIZARD', 'WOLVES', 'WONDER', 'WOODEN', 'WORKED', 'WORKER', 'WORLDS',
  'WORTHY', 'WRITER', 'WRITES', 'YELLOW', 'YIELDS', 'YOUTHS', 'HIKING',
  'BIKING', 'LIKING', 'MIKING', 'PIKING', 'SAKING', 'WAKING', 'BAKING',
  'CAKING', 'FAKING', 'LAKING', 'MAKING', 'RAKING', 'TAKING', 'DUKING',
  'LUKING', 'NUKING', 'PUKING', 'CUTING', 'FLUING', 'GLUING', 'TRUING',
  'BLUING', 'CLUING', 'CREWING', 'DREWING', 'FLEWING', 'GREWING', 'KNEWING',
  'BREWING', 'CHEWING', 'STEWING', 'VIEWING', 'WHEWING', 'BLEWING', 'SLEWING',
  'SPEWING', 'THEWING', 'SKEWING', 'SHEWING', 'PHEWING', 'MEWSING', 'NEWSING',
  'PEWSING', 'SEWSING', 'TEWSING', 'YEWSING', 'JEWSING', 'HEWSING', 'DEWSING',
  'FEWSING', 'LEWSING', 'REWSING', 'WEWSING', 'ZEWSING', 'HIKING', 'BIKING',
  'LIKING', 'MIKING', 'PIKING', 'SAKING', 'WAKING', 'BAKING', 'CAKING',
  'FAKING', 'LAKING', 'MAKING', 'RAKING', 'TAKING', 'DUKING', 'LUKING',
  'NUKING', 'PUKING', 'CUTING', 'FLUING', 'GLUING', 'TRUING', 'BLUING',
  'CLUING', 'CREWING', 'DREWING', 'FLEWING', 'GREWING', 'KNEWING', 'BREWING',
  'CHEWING', 'STEWING', 'VIEWING', 'WHEWING', 'BLEWING', 'SLEWING', 'SPEWING',
  'THEWING', 'SKEWING', 'SHEWING', 'PHEWING', 'MEWSING', 'NEWSING', 'PEWSING',
  'SEWSING', 'TEWSING', 'YEWSING', 'JEWSING', 'HEWSING', 'DEWSING', 'FEWSING',
  'LEWSING', 'REWSING', 'WEWSING', 'ZEWSING', 'HIKERS', 'BIKERS', 'LIKERS',
  'MIKERS', 'PIKERS', 'SAKERS', 'WAKERS', 'BAKERS', 'CAKERS', 'FAKERS',
  'LAKERS', 'MAKERS', 'RAKERS', 'TAKERS', 'DUKERS', 'LUKERS', 'NUKERS',
  'PUKERS', 'CUTERS', 'FLUERS', 'GLUERS', 'TRUERS', 'BLUERS', 'CLUERS',
  'CREWERS', 'DREWERS', 'FLEWERS', 'GREWERS', 'KNEWERS', 'BREWERS', 'CHEWERS',
  'STEWERS', 'VIEWERS', 'WHEWERS', 'BLEWERS', 'SLEWERS', 'SPEWERS', 'THEWERS',
  'SKEWERS', 'SHEWERS', 'PHEWERS', 'MEWSERS', 'NEWSERS', 'PEWSERS', 'SEWSERS',
  'TEWSERS', 'YEWSERS', 'JEWSERS', 'HEWSERS', 'DEWSERS', 'FEWSERS', 'LEWSERS',
  'REWSERS', 'WEWSERS', 'ZEWSERS'
]);

export function initializeGameFromPuzzle(puzzle: GeneratedPuzzle): GameState {
  const blocks: GameBlock[][] = [];
  
  for (let row = 0; row < puzzle.gridSize; row++) {
    const blockRow: GameBlock[] = [];
    for (let col = 0; col < puzzle.gridSize; col++) {
      blockRow.push({
        letter: puzzle.grid[row][col],
        id: `${row}-${col}`,
        row,
        col,
        isSelected: false,
        isHighlighted: false,
      });
    }
    blocks.push(blockRow);
  }

  return {
    grid: blocks,
    selectedBlocks: [],
    currentWord: '',
    score: 0,
    timer: 0,
    isGameComplete: false,
    gridSize: puzzle.gridSize,
    puzzleIndex: 0,
    solution: puzzle.solution,
    solutionPaths: puzzle.solutionPaths,
    removedWords: [],
    gameHistory: [blocks.map(row => row.map(block => ({ ...block })))]
  };
}

export function isValidWord(word: string): boolean {
  return WORD_DICTIONARY.has(word.toUpperCase());
}

export function applyGravity(grid: GameBlock[][]): GameBlock[][] {
  const newGrid = grid.map(row => row.map(block => ({ ...block })));
  const gridSize = newGrid.length;

  // Apply gravity column by column
  for (let col = 0; col < gridSize; col++) {
    const column: GameBlock[] = [];
    
    // Collect non-empty blocks from bottom to top
    for (let row = gridSize - 1; row >= 0; row--) {
      if (newGrid[row][col].letter && newGrid[row][col].letter !== '') {
        column.push({ ...newGrid[row][col] });
      }
    }
    
    // Clear the column
    for (let row = 0; row < gridSize; row++) {
      newGrid[row][col] = {
        letter: '',
        id: `${row}-${col}`,
        row,
        col,
        isSelected: false,
        isHighlighted: false,
      };
    }
    
    // Fill from bottom with collected blocks
    for (let i = 0; i < column.length; i++) {
      const targetRow = gridSize - 1 - i;
      newGrid[targetRow][col] = {
        ...column[i],
        row: targetRow,
        id: `${targetRow}-${col}`,
        isSelected: false,
        isHighlighted: false,
      };
    }
  }

  return newGrid;
}

export function removeSelectedBlocks(grid: GameBlock[][], selectedBlocks: GameBlock[]): GameBlock[][] {
  const newGrid = grid.map(row => row.map(block => ({ ...block })));
  
  // Remove selected blocks
  selectedBlocks.forEach(block => {
    newGrid[block.row][block.col] = {
      letter: '',
      id: `${block.row}-${block.col}`,
      row: block.row,
      col: block.col,
      isSelected: false,
      isHighlighted: false,
    };
  });
  
  // Apply gravity
  return applyGravity(newGrid);
}

export function isGameComplete(grid: GameBlock[][]): boolean {
  return grid.every(row => 
    row.every(block => !block.letter || block.letter === '')
  );
}

export function areBlocksAdjacent(block1: GameBlock, block2: GameBlock): boolean {
  const rowDiff = Math.abs(block1.row - block2.row);
  const colDiff = Math.abs(block1.col - block2.col);
  
  // Adjacent means exactly one step in orthogonal directions only (no diagonals)
  return (rowDiff === 1 && colDiff === 0) || (rowDiff === 0 && colDiff === 1);
}

export function isValidWordPath(blocks: GameBlock[]): boolean {
  if (blocks.length < 2) return true;
  
  for (let i = 1; i < blocks.length; i++) {
    if (!areBlocksAdjacent(blocks[i - 1], blocks[i])) {
      return false;
    }
  }
  
  return true;
}

export function getHint(
  currentGrid: GameBlock[][], 
  solution: string[], 
  solutionPaths: number[][][], 
  removedWords: string[]
): { word: string; path: number[][] } | null {
  
  // Check if all removed words are part of the solution
  for (const removedWord of removedWords) {
    if (!solution.includes(removedWord)) {
      return null; // No hint available - removed word not in solution
    }
  }
  
  // Find the next word in the solution that hasn't been removed
  for (let i = 0; i < solution.length; i++) {
    const word = solution[i];
    if (!removedWords.includes(word)) {
      // Check if this word is still available in the current grid
      const path = solutionPaths[i];
      let wordAvailable = true;
      
      for (const [row, col] of path) {
        if (!currentGrid[row] || !currentGrid[row][col] || 
            currentGrid[row][col].letter !== word[path.indexOf([row, col])]) {
          wordAvailable = false;
          break;
        }
      }
      
      if (wordAvailable) {
        return { word, path };
      }
    }
  }
  
  return null;
}

export function canUndoLastMove(gameHistory: GameBlock[][][]): boolean {
  return gameHistory.length > 1;
}

export function undoLastMove(gameHistory: GameBlock[][][]): GameBlock[][] {
  if (gameHistory.length <= 1) {
    return gameHistory[0] || [];
  }
  
  // Return the previous state
  return gameHistory[gameHistory.length - 2].map(row => 
    row.map(block => ({ ...block }))
  );
}

export function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

export function calculateScore(wordLength: number, timeBonus: number = 0): number {
  const baseScore = wordLength * 10;
  const lengthBonus = wordLength > 4 ? (wordLength - 4) * 5 : 0;
  return baseScore + lengthBonus + timeBonus;
}